/**
 * Generated by Forma LVGL Renderer
 * This file contains LVGL UI code generated from .fml definitions
 */

#include "lvgl.h"
#include <stdint.h>
#include <stdbool.h>

/* Platform-specific includes */
#include <unistd.h>

/* Event Callbacks (Internal) */
/* UI Widgets (Internal) */
static lv_obj_t *button_0 = NULL;

/**
 * Initialize the Forma UI system
 * Call this once during application startup
 */
void forma_init(void) {
    button_0 = lv_btn_create(lv_scr_act());
    lv_label_set_text(button_0, "Hello");
    lv_obj_set_width(button_0, 100);
    lv_obj_set_height(button_0, 50);
}

/**
 * Run the Forma UI main loop
 * This function handles platform-specific event processing
 */
void forma_run(void) {
    /* Linux: LVGL event loop */
    while (1) {
        lv_timer_handler();
        usleep(5000);
    }
}

