// Example: Using the Tracer Plugin
// This demonstrates all the features of the tracer plugin

#include "../src/tracer_plugin.hpp"
#include <thread>
#include <chrono>

using namespace forma::tracer;

void simulate_compilation() {
    auto& tracer = get_tracer();
    
    // Stage 1: Reading
    tracer.begin_stage("Reading source file");
    tracer.verbose("File: example.forma");
    tracer.stat("File size", 1234);
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    tracer.end_stage();
    
    // Stage 2: Parsing  
    tracer.begin_stage("Parsing");
    tracer.debug("Initializing parser...");
    std::this_thread::sleep_for(std::chrono::milliseconds(200));
    tracer.stat("Types", 3);
    tracer.stat("Instances", 15);
    tracer.debug("Parser complete");
    tracer.end_stage();
    
    // Stage 3: Type checking (with warnings)
    tracer.begin_stage("Type checking");
    std::this_thread::sleep_for(std::chrono::milliseconds(150));
    tracer.warning("Unused variable 'x' in MyWidget");
    tracer.info("Type checking complete");
    tracer.end_stage();
    
    // Stage 4: Code generation
    tracer.begin_stage("Code generation");
    tracer.verbose("Renderer: LVGL");
    tracer.debug("Generating widget code...");
    std::this_thread::sleep_for(std::chrono::milliseconds(250));
    tracer.stat("Generated bytes", 5432);
    tracer.end_stage();
    
    tracer.success("Compilation successful");
    tracer.info("  Output: example.c");
}

void simulate_compilation_with_errors() {
    auto& tracer = get_tracer();
    
    tracer.begin_stage("Type checking");
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    
    tracer.error("Property 'text' expects String, got Number");
    tracer.error("Unknown property 'invalid_prop' in Button");
    
    tracer.failure("Type checking failed");
    tracer.failure("Compilation failed with 2 error(s)");
}

int main() {
    auto& tracer = get_tracer();
    
    std::cout << "=================================================\n";
    std::cout << "         Tracer Plugin Examples\n";
    std::cout << "=================================================\n\n";
    
    // Example 1: Normal mode
    std::cout << "Example 1: NORMAL MODE\n";
    std::cout << "----------------------\n";
    tracer.set_level(TraceLevel::Normal);
    simulate_compilation();
    
    std::cout << "\n\n";
    
    // Example 2: Verbose mode
    std::cout << "Example 2: VERBOSE MODE\n";
    std::cout << "-----------------------\n";
    tracer.set_level(TraceLevel::Verbose);
    simulate_compilation();
    
    std::cout << "\n\n";
    
    // Example 3: Debug mode
    std::cout << "Example 3: DEBUG MODE\n";
    std::cout << "---------------------\n";
    tracer.set_level(TraceLevel::Debug);
    simulate_compilation();
    
    std::cout << "\n\n";
    
    // Example 4: Error handling (always visible)
    std::cout << "Example 4: ERROR HANDLING (Silent mode)\n";
    std::cout << "----------------------------------------\n";
    tracer.set_level(TraceLevel::Silent);
    simulate_compilation_with_errors();
    
    std::cout << "\n\n";
    std::cout << "=================================================\n";
    std::cout << "Plugin: " << get_plugin_name() << " v" << get_plugin_version() << "\n";
    std::cout << "=================================================\n";
    
    return 0;
}
