/**
 * Generated by Forma LVGL Renderer
 * This file contains LVGL UI code generated from .fml definitions
 */

#include "lvgl.h"
#include <stdint.h>
#include <stdbool.h>

/* Platform-specific includes */
#include <unistd.h>

/* Bundled Assets */
extern const unsigned char asset_assets_logo_png[];
extern const unsigned int asset_assets_logo_png_size;
extern const unsigned char asset_assets_icons_settings_png[];
extern const unsigned int asset_assets_icons_settings_png_size;

/* Event Callbacks (Internal) */
/* UI Widgets (Internal) */
static lv_obj_t *image_0 = NULL;
static lv_obj_t *image_1 = NULL;
static lv_obj_t *label_2 = NULL;
static lv_obj_t *button_3 = NULL;

/**
 * Initialize the Forma UI system
 * Call this once during application startup
 */
void forma_init(void) {
    image_0 = lv_img_create(lv_scr_act());
    lv_obj_set_x(image_0, 10);
    lv_obj_set_y(image_0, 10);
    lv_obj_set_width(image_0, 200);
    lv_obj_set_height(image_0, 150);
    lv_img_set_src(image_0, asset_assets_logo_png);    
    image_1 = lv_img_create(lv_scr_act());
    lv_obj_set_x(image_1, 10);
    lv_obj_set_y(image_1, 170);
    lv_obj_set_width(image_1, 100);
    lv_obj_set_height(image_1, 100);
    lv_img_set_src(image_1, asset_assets_icons_settings_png);    
    button_3 = lv_btn_create(lv_scr_act());
    lv_obj_set_x(button_3, 120);
    lv_obj_set_y(button_3, 170);
    lv_obj_set_width(button_3, 150);
    lv_obj_set_height(button_3, 50);
    label_2 = lv_label_create(button_3);
    lv_label_set_text(label_2, "Click Me");
}

/**
 * Run the Forma UI main loop
 * This function handles platform-specific event processing
 */
void forma_run(void) {
    /* Linux: LVGL event loop */
    while (1) {
        lv_timer_handler();
        usleep(5000);
    }
}

