/**
 * Generated by Forma LVGL Renderer
 * This file contains LVGL UI code generated from .fml definitions
 */

#include "lvgl.h"
#include <stdint.h>
#include <stdbool.h>

/* Platform-specific includes */
#include <unistd.h>

/* Event Callbacks (Internal) */
/* UI Widgets (Internal) */
static lv_obj_t *label_0 = NULL;
static lv_obj_t *button_1 = NULL;

/**
 * Initialize the Forma UI system
 * Call this once during application startup
 */
void forma_init(void) {
    button_1 = lv_btn_create(lv_scr_act());
    label_0 = lv_label_create(button_1);
    lv_label_set_text(label_0, "Hello");
}

/**
 * Run the Forma UI main loop
 * This function handles platform-specific event processing
 */
void forma_run(void) {
    /* Linux: LVGL event loop */
    while (1) {
        lv_timer_handler();
        usleep(5000);
    }
}

