#pragma once

#include <parser/ir.hpp>
#include <toml/toml.hpp>
#include <string>
#include <sstream>
#include <fstream>
#include <filesystem>
#include "sdl3_downloader.hpp"
#include "lvgl_downloader.hpp"

namespace forma::lvgl_native {

class LVGLNativeRenderer {
public:
    LVGLNativeRenderer() = default;
    
    bool render(const void* doc, const char* input_path, const char* output_path) {
        (void)doc;        // Unused - this plugin only generates the wrapper
        
        // Read configuration from forma.toml
        std::string sdl3_version = "3.1.6";  // Default
        std::string lvgl_version = "9.2.2";  // Default
        
        if (input_path) {
            std::filesystem::path input_file(input_path);
            std::filesystem::path config_path = input_file.parent_path() / "forma.toml";
            
            if (std::filesystem::exists(config_path)) {
                std::ifstream config_file(config_path);
                std::string config_content((std::istreambuf_iterator<char>(config_file)),
                                          std::istreambuf_iterator<char>());
                
                auto toml_doc = forma::toml::parse(config_content);

                // Preferred schema (supported by the current parser):
                // [native-lvgl]
                // sdl3_version = "3.1.6"
                // lvgl_version = "9.2.2"
                if (auto tbl = toml_doc.get_table("native-lvgl")) {
                    if (auto v = tbl->get_string("sdl3_version")) sdl3_version = std::string(*v);
                    if (auto v = tbl->get_string("lvgl_version")) lvgl_version = std::string(*v);
                }
                else if (auto plugins_tbl = toml_doc.get_table("plugins")) {
                    // Fallback: keys inside [plugins] using flat names
                    // plugins.native-lvgl is NOT supported by the current TOML parser,
                    // so we allow keys like:
                    // [plugins]
                    // native-lvgl_sdl3_version = "3.1.6"
                    // native-lvgl_lvgl_version = "9.2.2"
                    if (auto v = plugins_tbl->get_string("native-lvgl_sdl3_version")) sdl3_version = std::string(*v);
                    if (auto v = plugins_tbl->get_string("native-lvgl_lvgl_version")) lvgl_version = std::string(*v);
                }
                else {
                    // Last resort: top-level keys
                    if (auto v = toml_doc.root.get_string("sdl3_version")) sdl3_version = std::string(*v);
                    if (auto v = toml_doc.root.get_string("lvgl_version")) lvgl_version = std::string(*v);
                }
            }
        }
        
        // Download dependencies if needed
        if (!forma::sdl3::download_sdl3(sdl3_version)) {
            std::cerr << "Failed to download SDL3\n";
            return false;
        }
        
        if (!forma::lvgl::download_lvgl(lvgl_version)) {
            std::cerr << "Failed to download LVGL\n";
            return false;
        }
        
        std::ostringstream code;
        
        // Generate header comment
        code << "/* Generated by Forma - SDL3 + LVGL Initialization Wrapper */\n";
        code << "/* This file provides forma_init() to set up SDL3 and LVGL */\n\n";
        
        // Generate includes
        code << "#include \"lvgl/lvgl.h\"\n";
        code << "#include <SDL3/SDL.h>\n";
        code << "#include <stdio.h>\n\n";
        
        // Generate forma_init function for SDL3 + LVGL setup
        code << generate_forma_init();
        
        // Write output file
        std::ofstream out(output_path);
        if (!out.is_open()) {
            return false;
        }
        out << code.str();
        out.close();
        
        return true;
    }
    
private:
    std::string generate_forma_init() {
        std::ostringstream init;
        
        init << "/**\n";
        init << " * Initialize SDL3 and LVGL for native desktop applications.\n";
        init << " * \n";
        init << " * This function must be called before any LVGL operations.\n";
        init << " * It sets up SDL3 window, renderer, and LVGL display with SDL3 backend.\n";
        init << " * \n";
        init << " * @return 0 on success, -1 on failure\n";
        init << " */\n";
        init << "int forma_init(void) {\n";
        init << "    /* Initialize SDL3 */\n";
        init << "    if (!SDL_Init(SDL_INIT_VIDEO)) {\n";
        init << "        fprintf(stderr, \"SDL3 initialization failed: %s\\n\", SDL_GetError());\n";
        init << "        return -1;\n";
        init << "    }\n\n";
        
        init << "    /* Create SDL window */\n";
        init << "    SDL_Window* window = SDL_CreateWindow(\n";
        init << "        \"Forma Application\",\n";
        init << "        800, 480,\n";
        init << "        SDL_WINDOW_RESIZABLE\n";
        init << "    );\n";
        init << "    if (!window) {\n";
        init << "        fprintf(stderr, \"Window creation failed: %s\\n\", SDL_GetError());\n";
        init << "        SDL_Quit();\n";
        init << "        return -1;\n";
        init << "    }\n\n";
        
        init << "    /* Create SDL renderer */\n";
        init << "    SDL_Renderer* renderer = SDL_CreateRenderer(window, NULL);\n";
        init << "    if (!renderer) {\n";
        init << "        fprintf(stderr, \"Renderer creation failed: %s\\n\", SDL_GetError());\n";
        init << "        SDL_DestroyWindow(window);\n";
        init << "        SDL_Quit();\n";
        init << "        return -1;\n";
        init << "    }\n\n";
        
        init << "    /* Initialize LVGL */\n";
        init << "    lv_init();\n\n";
        
        init << "    /* Create LVGL display with SDL3 backend */\n";
        init << "    lv_display_t* display = lv_sdl_window_create(800, 480);\n";
        init << "    if (!display) {\n";
        init << "        fprintf(stderr, \"LVGL display creation failed\\n\");\n";
        init << "        SDL_DestroyRenderer(renderer);\n";
        init << "        SDL_DestroyWindow(window);\n";
        init << "        SDL_Quit();\n";
        init << "        return -1;\n";
        init << "    }\n\n";
        
        init << "    /* Create LVGL input devices */\n";
        init << "    lv_indev_t* mouse = lv_sdl_mouse_create();\n";
        init << "    lv_indev_t* mousewheel = lv_sdl_mousewheel_create();\n";
        init << "    lv_indev_t* keyboard = lv_sdl_keyboard_create();\n\n";
        
        init << "    (void)mouse;      /* Suppress unused variable warnings */\n";
        init << "    (void)mousewheel;\n";
        init << "    (void)keyboard;\n\n";
        
        init << "    printf(\"SDL3 and LVGL initialized successfully\\n\");\n";
        init << "    return 0;\n";
        init << "}\n";
        
        return init.str();
    }
};

} // namespace forma::lvgl_native

// Plugin interface
extern "C" {
    bool forma_render(const void* doc, const char* input_path, const char* output_path) {
        forma::lvgl_native::LVGLNativeRenderer renderer;
        return renderer.render(doc, input_path, output_path);
    }
    
    uint64_t forma_plugin_metadata_hash() {
        return FORMA_PLUGIN_METADATA_HASH;
    }
}
